[[whisper_cpp]]
arch = "aarch64"
git-tree-sha1 = "c0f418987482cd25305d22306db8e782979ba672"
os = "macos"

    [[whisper_cpp.download]]
    sha256 = "2175e0b46be3877d9a1a9e21789146136c7a1aec8e099019824df1d2ee00316c"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.aarch64-apple-darwin.tar.gz"
[[whisper_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a44e54229bd02f4ba183f4ff2ba7ca60ab88df20"
libc = "glibc"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "0370eabfe5d79f9a7c7d79370eafc8d1fb230a1ea69f83a2799e4c97ed44a8f4"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[whisper_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbc256f1eab35ecbdbecaa90d1643a394cedae89"
libc = "glibc"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "5c38cfddff8047032401b4791a82db7efcbede611d8dbebee5be75c7fb273bf3"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[whisper_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19e84a108f6726a387146e66d2a0749a29ded405"
libc = "musl"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "e6d1430c057062721740c8b62d4be36c41ad2ac6ceba0cdd56f2f66ee8f54224"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[whisper_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1270c866baa88702232637e5d7ac26de75aab93e"
libc = "musl"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "40a0a628034ff4a46debb35ca8f59dbbaad22196afe4ec1cbac88149f1ae7ce9"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[whisper_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b213312f27c09df53aee024ee6bffce93d9c0b0"
libc = "glibc"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "38d7ca3c310565b9f83926f5125bf6dba370b555f23a55ada6a6f58a642cbfd5"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.i686-linux-gnu-cxx03.tar.gz"
[[whisper_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fc5f3b196013a86a6b954c2c95b94a8c0d09f25"
libc = "glibc"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "72e3947a063dc5238e12d02b7c6d85371d1fb51fa917d06d543cad1c2e521e8d"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.i686-linux-gnu-cxx11.tar.gz"
[[whisper_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59fdf989386aec66496f62946b6f1d427a5b8bef"
libc = "musl"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "1bd0f68943e4ad019d73c3aa39eb96d5c763d765a4f6680cf5b30494d0beecfb"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.i686-linux-musl-cxx03.tar.gz"
[[whisper_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73e62f97601fca2fb7bb7b83b888a8f0e620d15d"
libc = "musl"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "9a715f935e827b5f9b45970734d3da9ffede3a1a593b00a6d4cabd3b404addcd"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.i686-linux-musl-cxx11.tar.gz"
[[whisper_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57d377cd47ed247748d038d9d279a970c74958e0"
os = "windows"

    [[whisper_cpp.download]]
    sha256 = "9496aa159c77c58527cf84db7efff9ccbcdddae2fa4d5fd42134790050b5d681"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[whisper_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c8b570d9a781d0c6c29d1a556e66ebd564fd63c"
os = "windows"

    [[whisper_cpp.download]]
    sha256 = "7245f2d23409b31643721d82d2836029bbd94bc3048d36f94b132b46f3611808"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
git-tree-sha1 = "d7d78d2543e672dff6fa331d1a90e08e90d180e1"
os = "macos"

    [[whisper_cpp.download]]
    sha256 = "cae9ad69c4fd9462ab5422f86f7394439dbb2279bec32a589722869812762e53"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-apple-darwin.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "083aebcee36284bd7963b649f1974ee00df73469"
libc = "glibc"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "e1ba66244c51c68d0ddb94773cc592f43259ad6209153e3c93e9f97a9373f647"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fabd2c299d6c09c20407931d919dc1568e2bdc0"
libc = "glibc"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "cef4b50913241dc7618fd798ecbf3465ddbea20ec313eb8ff1657b615b613f54"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9968f8dfe7bcc79d6d9f179c4ee914151f84f55b"
libc = "musl"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "98768f1a253e11e0baa15af2d8f92b4c8f925b95ff6e721ce5eb82e828b71bba"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16cfe604ceb93cd90a61d532610ea7e673498cae"
libc = "musl"
os = "linux"

    [[whisper_cpp.download]]
    sha256 = "0578a326fa22858abe79a270ba76c71b45e59dafaf86bc2d91ae522e55ee4559"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
git-tree-sha1 = "f515a7306fbab569f21fe180e5ad20a97e44410f"
os = "freebsd"

    [[whisper_cpp.download]]
    sha256 = "c51ee09f1be6e40f2d1303db23447bc4d94356507ea8943629f3c5cf67b01ea5"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "738b69fd05ee3e60e08ae3c4b43d5ff548299b84"
os = "windows"

    [[whisper_cpp.download]]
    sha256 = "f0b1fab7cf92ae596a9d42508879fcc9080cba4af4a2bd93f1d0ee4902707aac"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[whisper_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebb345dfddbfee8340d9e0d0974600d9e185986b"
os = "windows"

    [[whisper_cpp.download]]
    sha256 = "d4332190aaf2d15ec5f3f6bb6c6515e41ed8f9b4d038c79bc0342a12ff9cf20d"
    url = "https://github.com/JuliaBinaryWrappers/whisper_cpp_jll.jl/releases/download/whisper_cpp-v1.2.0+0/whisper_cpp.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
