# Autogenerated wrapper script for whisper_cpp_jll for aarch64-apple-darwin
export libggml, libggml_base, libggml_cpu, libggml_metal, libparakeet, libwhisper, whisper_bench, whisper_cli, whisper_quantize

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("whisper_cpp")
JLLWrappers.@declare_library_product(libggml, "@rpath/libggml.0.dylib")
JLLWrappers.@declare_library_product(libggml_base, "@rpath/libggml-base.0.dylib")
JLLWrappers.@declare_library_product(libggml_cpu, "@rpath/libggml-cpu.0.dylib")
JLLWrappers.@declare_library_product(libggml_metal, "@rpath/libggml-metal.0.dylib")
JLLWrappers.@declare_library_product(libparakeet, "@rpath/libparakeet.1.dylib")
JLLWrappers.@declare_library_product(libwhisper, "@rpath/libwhisper.1.dylib")
JLLWrappers.@declare_executable_product(whisper_bench)
JLLWrappers.@declare_executable_product(whisper_cli)
JLLWrappers.@declare_executable_product(whisper_quantize)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libggml,
        "lib/libggml.0.20.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_base,
        "lib/libggml-base.0.20.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_cpu,
        "lib/libggml-cpu.0.20.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_metal,
        "lib/libggml-metal.0.20.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparakeet,
        "lib/libparakeet.1.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwhisper,
        "lib/libwhisper.1.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        whisper_bench,
        "bin/whisper-bench",
    )

    JLLWrappers.@init_executable_product(
        whisper_cli,
        "bin/whisper-cli",
    )

    JLLWrappers.@init_executable_product(
        whisper_quantize,
        "bin/whisper-quantize",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
