# Autogenerated wrapper script for whisper_cpp_jll for aarch64-unknown-freebsd
export libggml, libggml_base, libggml_cpu, libparakeet, libwhisper, whisper_bench, whisper_cli, whisper_quantize

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("whisper_cpp")
JLLWrappers.@declare_library_product(libggml, "libggml.so.0")
JLLWrappers.@declare_library_product(libggml_base, "libggml-base.so.0")
JLLWrappers.@declare_library_product(libggml_cpu, "libggml-cpu.so.0")
JLLWrappers.@declare_library_product(libparakeet, "libparakeet.so.1")
JLLWrappers.@declare_library_product(libwhisper, "libwhisper.so.1")
JLLWrappers.@declare_executable_product(whisper_bench)
JLLWrappers.@declare_executable_product(whisper_cli)
JLLWrappers.@declare_executable_product(whisper_quantize)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libggml,
        "lib/libggml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_base,
        "lib/libggml-base.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_cpu,
        "lib/libggml-cpu.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparakeet,
        "lib/libparakeet.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwhisper,
        "lib/libwhisper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        whisper_bench,
        "bin/whisper-bench",
    )

    JLLWrappers.@init_executable_product(
        whisper_cli,
        "bin/whisper-cli",
    )

    JLLWrappers.@init_executable_product(
        whisper_quantize,
        "bin/whisper-quantize",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
