# Autogenerated wrapper script for whisper_cpp_jll for i686-w64-mingw32-cxx11
export libwhisper

JLLWrappers.@generate_wrapper_header("whisper_cpp")
JLLWrappers.@declare_library_product(libwhisper, "libwhisper.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwhisper,
        "bin\\libwhisper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
