# Autogenerated wrapper script for whisper_cpp_jll for x86_64-w64-mingw32-cxx11
export libggml, libggml_base, libggml_cpu, libparakeet, libwhisper, whisper_bench, whisper_cli, whisper_quantize

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("whisper_cpp")
JLLWrappers.@declare_library_product(libggml, "ggml.dll")
JLLWrappers.@declare_library_product(libggml_base, "ggml-base.dll")
JLLWrappers.@declare_library_product(libggml_cpu, "ggml-cpu.dll")
JLLWrappers.@declare_library_product(libparakeet, "libparakeet.dll")
JLLWrappers.@declare_library_product(libwhisper, "libwhisper.dll")
JLLWrappers.@declare_executable_product(whisper_bench)
JLLWrappers.@declare_executable_product(whisper_cli)
JLLWrappers.@declare_executable_product(whisper_quantize)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libggml,
        "bin\\ggml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_base,
        "bin\\ggml-base.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libggml_cpu,
        "bin\\ggml-cpu.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparakeet,
        "bin\\libparakeet.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwhisper,
        "bin\\libwhisper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        whisper_bench,
        "bin\\whisper-bench.exe",
    )

    JLLWrappers.@init_executable_product(
        whisper_cli,
        "bin\\whisper-cli.exe",
    )

    JLLWrappers.@init_executable_product(
        whisper_quantize,
        "bin\\whisper-quantize.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
